spring.application.name=ReForest

# Conexion a MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/reforest
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Logs a fichero
logging.file.name=logs/reforest.log
logging.level.root=INFO
logging.level.com.sanvalero.reforest=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# Configuracion de Jackson para mapeo de JSON
spring.jackson.property-naming-strategy=SNAKE_CASE

# Configuracion de Swagger/OpenAPI con un archivo YAML estatico
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.url=/openapi.yaml
springdoc.api-docs.enabled=false
